### ISSUE TITLE
Remote deployed PFE missing PVC for codewind-workspace

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind#1294]
**Codewind version:** master
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**

PFE deployed remotely via `cwctl`, it does not have a PVC mount for the `/codewind-workspace`

```
     volumeMounts:
        - name: buildah-volume
          mountPath: /var/lib/containers
        - name: registry-secret
          mountPath: /tmp/secret
        - name: codewind-k3hgc5ov-token-bt8zv
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
```

As a result, appsody projects are failing to start with message:

```
persistentvolumeclaim "codewind-k3hhnuhf" not found
```

**Steps to reproduce:**

**Workaround:**
