### ISSUE TITLE
Plugin runtime crashed unexpectedly in Che/Codewind workspace

### ISSUE THREAD

**Issue by tam512** [eclipse/codewind#1664]
**Codewind version:** 0.6.0
**OS:** Red Hat

**Che version:** 7.4.0
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:** OCP 4.2
List of plugins and editors:
- eclipse/CodewindPlugin/0.6.0 - Enables iterative development and deployment in Che
- eclipse/codewind-plugin/0.6.0 - Codewind Extension for Theia
- eclipse/che-machine-exec-plugin/7.3.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace containers.
- eclipse/che-theia/7.3.1 - Eclipse Theia

**Description:**
Codewind workspace crashed with the following message:

![image](https://user-images.githubusercontent.com/22480038/71992946-e367bb80-31fb-11ea-9700-ed093dc2715a.png)

**Steps to reproduce:**
- Enable Che via Kabanero 0.3.0 (_spec.che.enable: true_)
- Create workspace using devfile
http://<che ingress domain>/f?url=https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.6.0/devfiles/0.6.0/devfile.yaml
- Create a java microProfile project in Codewind workspace
- Let the workspace up over night, the next day I see that codewind crash with the following message. I've also seen this error when having 5 projects (java MP, Springboot, nodejs, express, loopback) running in codewind workspace

- Use the following Che custom properties in CheCluster:
```
customCheProperties:
        CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN: "100"
        CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "0"
        CHE_WORKSPACE_PLUGIN__BROKER_WAIT__TIMEOUT__MIN: "5"

```

**Workaround:** 

- Stop/Start codewind workspace to recover
