### ISSUE TITLE
SVT:Che:Theia plugin is crashing intermittently on my OCP 4.2 cluster when I refresh my workspace from the browser

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1807]
**Codewind version:** 0.8.0
**OS:** CoreOS

**Che version:** 7.5.1
**IDE extension version:**  0.8.0
**IDE version:** Theia 7.5.1
**Kubernetes cluster:**
OCP 4.2 cluster on fyre

**Description:**
Codewind workspace is getting crashed intermittently. I created my workspace on Friday and let it open and I tried to access my workspace today and error says plugin crashed unexpectedly. 
If I keep refreshing browser it connected 2 times out of 10 times refresh. Here are screenshots and logs from this failure. 

```
Plugin runtime crashed unexpectedly, all plugins are not working, please reload the page. Probably there is not enough memory for the plugins. If it doesn't help, please check Theia server logs.
```

![Screen Shot 2020-01-19 at 5 49 02 PM](https://user-images.githubusercontent.com/713849/72690003-c7122b80-3ae5-11ea-97f8-bf9cf1f072b3.png)
![Screen Shot 2020-01-19 at 5 48 36 PM](https://user-images.githubusercontent.com/713849/72690004-c7122b80-3ae5-11ea-84c0-e853edfa67bf.png)
![Screen Shot 2020-01-19 at 5 47 54 PM](https://user-images.githubusercontent.com/713849/72690005-c7122b80-3ae5-11ea-83f0-523feb18bc39.png)

Logs:
[pfe.txt](https://github.com/eclipse/codewind/files/4083871/pfe.txt)
[theia-logs.txt](https://github.com/eclipse/codewind/files/4083872/theia-logs.txt)

**Steps to reproduce:**
1. Install Codewind using Che 7.5.1 on OCP cluster.
2. After session timeout, login to Che again.
3. I got into this failure.

**Workaround:**

**Comment by malincoln** [comment]
@johnmcollier pls review.  Thanks

**Comment by johnmcollier** [comment]
@jagraj Can you try the following things to see if it reduces how much Theia crashes?
- Increase the memory given to Theia in the 0.8.0 devfile from 1024Mi to 1536Mi. And if that doesn't help, try 2048Mi (see https://github.com/eclipse/codewind-che-plugin/blob/0af21bf34ff11d38edf68a7c450106e5869975da/devfiles/0.8.0/devfile.yaml#L20)
- If the above doesn't help, try removing the Java and Typescript LSP plugins we're adding in, they could be using up all of the memory in Theia.

**Comment by jagraj** [comment]
@johnmcollier 
I can not reproduce this problem from past couple of days, this seems to be intermittent and this is no longer stopship. Let us make this as hot for now and I will keep an eye on this.

**Comment by johnmcollier** [comment]
@jagraj Did increasing the memory available to Theia help?

**Comment by GeekArthur** [comment]
This is the related issue opened against Che https://github.com/eclipse/che/issues/14551 since other developers using Che hit this issue as well. From the issue, seems like it's related with "out of memory" and the fix from Che folks is only add hint to user which is the suggestion John mentions above.

**Comment by jagraj** [comment]
More info from my current Codewind workspace. I let it run over the weekend and I see pod is restarted 5 times and restarts are triggering from che-machine-exec9a8 container and not from other containers. Based on the data below we are getting into OOM condition which is happening all the time from this container. Does this container by default need more resources or there is actual memory leak causing this crash.?

```
  che-machine-exec9a8:
    Container ID:   cri-o://a748713eb2e6331bf432d6feee8d48493ea4e6125128ca04f345d60d0405977c
    Image:          quay.io/eclipse/che-machine-exec:7.5.1
    Image ID:       quay.io/eclipse/che-machine-exec@sha256:a4cd49870cc2595293f0682f88126142c5a1e83d03054b6aa3c9ede01921c11a
    Port:           4444/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 27 Jan 2020 03:04:32 -0800
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Sun, 26 Jan 2020 08:52:08 -0800
      Finished:     Mon, 27 Jan 2020 03:04:29 -0800
    Ready:          True
    Restart Count:  5
    Limits:
      memory:  134217728
    Requests:
      memory:  134217728
    Environment:
      CHE_WORKSPACE_NAME:                       codewind-cheh0lpf
      CHE_WORKSPACE_LOGS_ROOT__DIR:             /workspace_logs
```

**Comment by elsony** [comment]
@jagraj Do you happens to got a chance to try out increasing the memory available to Theia help or not yet?

**Comment by johnmcollier** [comment]
@jagraj When you can, please test with this devfile:
```
################################################################################
# Copyright (c) 2019 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
################################################################################
---
apiVersion: 1.0.0
metadata:
  name: codewind-che
components:
  - alias: theia-ide
    type: cheEditor
    id: eclipse/che-theia/latest
    memoryLimit: 1024Mi
  - alias: codewind-sidecar
    type: chePlugin
    reference: https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/plugins/codewind/codewind-sidecar/latest/meta.yaml
  - alias: codewind-theia
    type: chePlugin
    reference: https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/plugins/codewind/codewind-theia/latest/meta.yaml
```

**Comment by jagraj** [comment]
@johnmcollier 
Thanks, I created workspace with above devfile. I will monitor my cluster next few days to see if we still hit this crash issue.

**Comment by jagraj** [comment]
@johnmcollier 
After 25hrs i do not see any restarts of the containers from codewind workspace deployments.
I see only 3 containers and not 5 of them. What is our plan here if we do not see any restarts in next couple of days.?

```
NAME                                                              READY   STATUS    RESTARTS   AGE
che-575f9b99f-9krln                                               1/1     Running   0          45h
che-operator-b8c4d6676-xlxmh                                      1/1     Running   0          45h
codewind-performance-workspacei9cu2ib8x3nhphai-7774b85659-5r64n   1/1     Running   0          25h
codewind-workspacei9cu2ib8x3nhphai-d5dbcc46c-vvxkd                1/1     Running   0          25h
cw-gocw09ocp42svt-bb8f7170-474f-11ea-9b4d-5b4695ffbd-8vn22        1/1     Running   0          25h
cw-lagomcw09ocp42svt-c64a5490-474f-11ea-9b4d-f8cdd9cf7-ckd7p      1/1     Running   0          25h
cw-nodejscw09ocp42svt-d06e27d0-474f-11ea-9b4d-75cfc54748-wfb4p    1/1     Running   0          25h
cw-olcw09ocp42svt-df34f640-474f-11ea-9b4d-78bdd48b84-m69b2        1/1     Running   0          25h
cw-pythoncw09ocp42svt-e7e2f260-474f-11ea-9b4d-597f7b97c6-z268q    1/1     Running   0          25h
cw-springcw09ocp42svt-f2ac2d60-474f-11ea-9b4d-765549578d-qwgx9    1/1     Running   0          25h
cw-swiftcw09ocp42svt-ffbff4a0-474f-11ea-9b4d-84bcb948c-v9r6b      1/1     Running   0          24h
cw-wlcw09ocp42svt-0a2e1750-4750-11ea-9b4d-fc55d7dcb-qgdbz         1/1     Running   0          24h
devfile-registry-d8c7b7bcb-lqbpr                                  1/1     Running   0          45h
keycloak-6ccbf58f7c-c57gz                                         1/1     Running   0          45h
plugin-registry-5956f44994-fl8nl                                  1/1     Running   0          45h
postgres-5c654997d5-x49hh                                         1/1     Running   0          45h
workspacei9cu2ib8x3nhphai.che-jwtproxy-f44495869-8kdqz            1/1     Running   0          25h
workspacei9cu2ib8x3nhphai.che-workspace-pod-6cc6b89777-jsbbw      3/3     Running   0          25h
```

**Comment by elsony** [comment]
We'll probably need to try out adding the LSP back and increase the memory to see if it just doesn't have enough memory on the setup or there is memory leak on the LSP.

**Comment by jagraj** [comment]
@elsony
Thanks Elson. 

@johnmcollier 
Can you give me next version of devfile that we can test as part of our 0.9.0 test effort.?

**Comment by johnmcollier** [comment]
@jagraj Try this one with memory limits set for the LSPs:
```
################################################################################
# Copyright (c) 2019 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
################################################################################

---
apiVersion: 1.0.0
metadata:
  name: codewind-che
components:
  - alias: theia-ide
    type: cheEditor
    id: eclipse/che-theia/latest
    memoryLimit: 1024Mi
  - alias: codewind-sidecar
    type: chePlugin
    reference: https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/plugins/codewind/codewind-sidecar/latest/meta.yaml
  - alias: codewind-theia
    type: chePlugin
    reference: https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/plugins/codewind/codewind-theia/latest/meta.yaml
  - alias: node-plugin
    type: chePlugin
    id: che-incubator/typescript/latest
    memoryLimit: 1024Mi
  - alias: java-plugin
    type: chePlugin
    id: redhat/java11/latest
    memoryLimit: 1024Mi
```

**Comment by jagraj** [comment]
> @jagraj When you can, please test with this devfile:
> 
> ```
> ################################################################################
> # Copyright (c) 2019 IBM Corporation and others.
> # All rights reserved. This program and the accompanying materials
> # are made available under the terms of the Eclipse Public License v2.0
> # which accompanies this distribution, and is available at
> # http://www.eclipse.org/legal/epl-v20.html
> #
> # Contributors:
> #     IBM Corporation - initial API and implementation
> ################################################################################
> ---
> apiVersion: 1.0.0
> metadata:
>   name: codewind-che
> components:
>   - alias: theia-ide
>     type: cheEditor
>     id: eclipse/che-theia/latest
>     memoryLimit: 1024Mi
>   - alias: codewind-sidecar
>     type: chePlugin
>     reference: https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/plugins/codewind/codewind-sidecar/latest/meta.yaml
>   - alias: codewind-theia
>     type: chePlugin
>     reference: https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/plugins/codewind/codewind-theia/latest/meta.yaml
> ```

@johnmcollier 
I let it run 2 days with above workspace and I got into one restart from `che-machine-exec358` container due to OOM. Here is the info from the container.

```
 che-machine-exec358:
    Container ID:   cri-o://6c64a7084487a9c3e0b1eced5cf0699e15d1ce090d2584a3db2887c10ed082ec
    Image:          quay.io/eclipse/che-machine-exec:7.5.1
    Image ID:       quay.io/eclipse/che-machine-exec@sha256:9b31b0451dafa72e147abaae9756cb70da5bc8143301fb1079e149c09a8dd066
    Port:           4444/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 05 Feb 2020 17:43:28 -0800
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 04 Feb 2020 05:06:32 -0800
      Finished:     Wed, 05 Feb 2020 17:43:25 -0800
    Ready:          True
    Restart Count:  1
    Limits:
      memory:  134217728
    Requests:
      memory:  134217728
    Environment:
      CHE_WORKSPACE_NAME:                       codewind-che
      CHE_WORKSPACE_LOGS_ROOT__DIR:             /workspace_logs
```

**Comment by jagraj** [comment]
I see these messages for every second in che-machine container. 

```
QcUDUQRO5n3C3fmd2csxSmS2D19HEbyA1aB1l5VTrK2NuZO1kStC4_O52OQK4Y2PYJU5Rq9paQcK6M8WVNQ_56RKgaibzMUP3gFRH-IKRcwuIKIpw6jsUpXgz0Tkcv1p2bWAHEiuOw26nj7JDSMClcOgs6U0hJUaPhqXGRZn8Ix9Inh3ybspmmMto377rsPjcK3M6FngaZho9eTWB46A
[GIN] 2020/02/06 - 12:02:15 | 200 |    2.411526ms |     10.26.2.185 | GET      /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlaTljdTJpYjh4M25ocGhhaSJ9.eyJ3c2lkIjoid29ya3NwYWNlaTljdTJpYjh4M25ocGhhaSIsInVpZCI6IjFmMTUxODVlLTQyNzAtNDMyZS04Yzg3LWI2YzVmN2M5ZjgyNCIsImF1ZCI6IndvcmtzcGFjZWk5Y3UyaWI4eDNuaHBoYWkiLCJuYmYiOi0xLCJ1bmFtZSI6ImphZyIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNjEyMzU3NDkwLCJpYXQiOjE1ODA4MjE0OTAsImp0aSI6Ijk5MGUxOTAyLTI0MGEtNGZiYy05ZTVkLWFjMWZjMTY0NjRkMSJ9.Q3kL4X3LF3tXJBoeBgA7FxjuO3DDSVQMR5vCCJwwIEvA7dngDZFwVUvXS_X-pqxR4DRO30r874njY22QawwEd3ZFT3glgBI1Z6UDHLuSEGRVACm37kb_iPkJdLc56RfkRpQcUDUQRO5n3C3fmd2csxSmS2D19HEbyA1aB1l5VTrK2NuZO1kStC4_O52OQK4Y2PYJU5Rq9paQcK6M8WVNQ_56RKgaibzMUP3gFRH-IKRcwuIKIpw6jsUpXgz0Tkcv1p2bWAHEiuOw26nj7JDSMClcOgs6U0hJUaPhqXGRZn8Ix9Inh3ybspmmMto377rsPjcK3M6FngaZho9eTWB46A
[GIN] 2020/02/06 - 12:02:15 | 200 |    3.148694ms |     10.26.2.185 | GET      /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlaTljdTJpYjh4M25ocGhhaSJ9.eyJ3c2lkIjoid29ya3NwYWNlaTljdTJpYjh4M25ocGhhaSIsInVpZCI6IjFmMTUxODVlLTQyNzAtNDMyZS04Yzg3LWI2YzVmN2M5ZjgyNCIsImF1ZCI6IndvcmtzcGFjZWk5Y3UyaWI4eDNuaHBoYWkiLCJuYmYiOi0xLCJ1bmFtZSI6ImphZyIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNjEyMzU3NDkwLCJpYXQiOjE1ODA4MjE0OTAsImp0aSI6Ijk5MGUxOTAyLTI0MGEtNGZiYy05ZTVkLWFjMWZjMTY0NjRkMSJ9.Q3kL4X3LF3tXJBoeBgA7FxjuO3DDSVQMR5vCCJwwIEvA7dngDZFwVUvXS_X-pqxR4DRO30r874njY22QawwEd3ZFT3glgBI1Z6UDHLuSEGRVACm37kb_iPkJdLc56RfkRpQcUDUQRO5n3C3fmd2csxSmS2D19HEbyA1aB1l5VTrK2NuZO1kStC4_O52OQK4Y2PYJU5Rq9paQcK6M8WVNQ_56RKgaibzMUP3gFRH-IKRcwuIKIpw6jsUpXgz0Tkcv1p2bWAHEiuOw26nj7JDSMClcOgs6U0hJUaPhqXGRZn8Ix9Inh3ybspmmMto377rsPjcK3M6FngaZho9eTWB46A
[GIN] 2020/02/06 - 12:02:15 | 200 |     491.419µs |     10.26.2.185 | GET      /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlaTljdTJpYjh4M25ocGhhaSJ9.eyJ3c2lkIjoid29ya3NwYWNlaTljdTJpYjh4M25ocGhhaSIsInVpZCI6IjFmMTUxODVlLTQyNzAtNDMyZS04Yzg3LWI2YzVmN2M5ZjgyNCIsImF1ZCI6IndvcmtzcGFjZWk5Y3UyaWI4eDNuaHBoYWkiLCJuYmYiOi0xLCJ1bmFtZSI6ImphZyIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNjEyMzU3NDkwLCJpYXQiOjE1ODA4MjE0OTAsImp0aSI6Ijk5MGUxOTAyLTI0MGEtNGZiYy05ZTVkLWFjMWZjMTY0NjRkMSJ9.Q3kL4X3LF3tXJBoeBgA7FxjuO3DDSVQMR5vCCJwwIEvA7dngDZFwVUvXS_X-pqxR4DRO30r874njY22QawwEd3ZFT3glgBI1Z6UDHLuSEGRVACm37kb_iPkJdLc56RfkRpQcUDUQRO5n3C3fmd2csxSmS2D19HEbyA1aB1l5VTrK2NuZO1kStC4_O52OQK4Y2PYJU5Rq9paQcK6M8WVNQ_56RKgaibzMUP3gFRH-IKRcwuIKIpw6jsUpXgz0Tkcv1p2bWAHEiuOw26nj7JDSMClcOgs6U0hJUaPhqXGRZn8Ix9Inh3ybspmmMto377rsPjcK3M6FngaZho9eTWB46A
[GIN] 2020/02/06 - 12:02:15 | 200 |     783.134µs |     10.26.2.185 | GET      /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlaTljdTJpYjh4M25ocGhhaSJ9.eyJ3c2lkIjoid29ya3NwYWNlaTljdTJpYjh4M25ocGhhaSIsInVpZCI6IjFmMTUxODVlLTQyNzAtNDMyZS04Yzg3LWI2YzVmN2M5ZjgyNCIsImF1ZCI6IndvcmtzcGFjZWk5Y3UyaWI4eDNuaHBoYWkiLCJuYmYiOi0xLCJ1bmFtZSI6ImphZyIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNjEyMzU3NDkwLCJpYXQiOjE1ODA4MjE0OTAsImp0aSI6Ijk5MGUxOTAyLTI0MGEtNGZiYy05ZTVkLWFjMWZjMTY0NjRkMSJ9.Q3kL4X3LF3tXJBoeBgA7FxjuO3DDSVQMR5vCCJwwIEvA7dngDZFwVUvXS_X-pqxR4DRO30r874njY22QawwEd3ZFT3glgBI1Z6UDHLuSEGRVACm37kb_iPkJdLc56RfkRpQcUDUQRO5n3C3fmd2csxSmS2D19HEbyA1aB1l5VTrK2NuZO1kStC4_O52OQK4Y2PYJU5Rq9paQcK6M8WVNQ_56RKgaibzMUP3gFRH-IKRcwuIKIpw6jsUpXgz0Tkcv1p2bWAHEiuOw26nj7JDSMClcOgs6U0hJUaPhqXGRZn8Ix9Inh3ybspmmMto377rsPjcK3M6FngaZho9eTWB46A
[GIN] 2020/02/06 - 12:02:16 | 200 |     413.836µs |     10.26.2.185 | GET      /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlaTljdTJpYjh4M25ocGhhaSJ9.eyJ3c2lkIjoid29ya3NwYWNlaTljdTJpYjh4M25ocGhhaSIsInVpZCI6IjFmMTUxODVlLTQyNzAtNDMyZS04Yzg3LWI2YzVmN2M5ZjgyNCIsImF1ZCI6IndvcmtzcGFjZWk5Y3UyaWI4eDNuaHBoYWkiLCJuYmYiOi0xLCJ1bmFtZSI6ImphZyIsImlzcyI6IndzbWFzdGVyIiwiZXhwIjoxNjEyMzU3NDkwLCJpYXQiOjE1ODA4MjE0OTAsImp0aSI6Ijk5MGUxOTAyLTI0MGEtNGZiYy05ZTVkLWFjMWZjMTY0NjRkMSJ9.Q3kL4X3LF3tXJBoeBgA7FxjuO3DDSVQMR5vCCJwwIEvA7dngDZFwVUvXS_X-pqxR4DRO30r874njY22QawwEd3ZFT3glgBI1Z6UDHLuSEGRVACm37kb_iPkJdLc56RfkRpQcUDUQRO5n3C3fmd2csxSmS2D19HEbyA1aB1l5VTrK2NuZO1kStC4_O52OQK4Y2PYJU5Rq9paQcK6M8WVNQ_56RKgaibzMUP3gFRH-IKRcwuIKIpw6jsUpXgz0Tkcv1p2bWAHEiuOw26nj7JDSMClcOgs6U0hJUaPhqXGRZn8Ix9Inh3ybspmmMto377rsPjcK3M6FngaZho9eTWB46A
```

**Comment by rajivnathan** [comment]
@jagraj Since we're suspecting it could be something else causing the OOM issue, can you set up a plain workspace without the Codewind plugin and see if you hit the same problem? If you do hit it then we should probably just open an issue directly against Che.

**Comment by jagraj** [comment]
@rajivnathan 
Thanks, could you please share sample devfile that I can create workspace.?

**Comment by johnmcollier** [comment]
@jagraj 
```
################################################################################
# Copyright (c) 2019 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
################################################################################
---
apiVersion: 1.0.0
metadata:
  name: codewind-che
components:
  - alias: theia-ide
    type: cheEditor
    id: eclipse/che-theia/latest
    memoryLimit: 1024Mi
```

**Comment by jagraj** [comment]
I created new workspace with above devfile. I will monitor in next few days and see how this goes.

**Comment by jagraj** [comment]
It has been 3days 22hrs since default workspace has been running and there are no OOM container restarts with the above default Che workspace excluding Codewind plugins. Here are the pods and their status from my cluster. Codewind workspace Che-machine container restarted 6 times from 6 days hours. Do you think this  issue might be specific to Codewind workspace.?

**Comment by johnmcollier** [comment]
@jagraj One more devfile to try out:
```
---
apiVersion: 1.0.0
metadata:
  name: codewind-che
components:
  - alias: theia-ide
    type: cheEditor
    id: eclipse/che-theia/latest
    memoryLimit: 1024Mi
  - alias: node-plugin
    type: chePlugin
    id: che-incubator/typescript/latest
    memoryLimit: 1024Mi
  - alias: java-plugin
    type: chePlugin
    id: redhat/java11/latest
    memoryLimit: 1024Mi
```

This time, no Codewind plugins, but two Theia plugins/LSPs installed.
