### ISSUE TITLE
SVT:[Hybrid]:Missing Tekton configuration for Hybrid codewind.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#1849]
**Codewind version:** 0.8.0
**OS:** WIndows/Mac/Linux

**Che version:** 
**IDE extension version:** 0.8.0
**IDE version:** All plugins
**Kubernetes cluster:**

OCP 4.2

**Description:**
In 0.8.0 release we enabled "Tekton Dashboard" for remote codewind install, after doing more debugging and found out that we need to apply Cluster roles and Cluster role bindings for the namespace where we are installing remote codewind. We have two options here, one is let `cwctl` provide options to the user to enable Tekton Pipelines by applying roles and bindings. This is too late for 0.8.0 release but we can provide instructions to the user to apply cluster roles and bindings. 

**Steps to reproduce:**
1. Install remote codewind.
2. On VSCode or Eclipse click on Tekton Dashboard then it will fail to open Tekton Dashboard.

**Workaround:**

**Comment by tobespc** [comment]
what are you after here @jagraj for this release ?  just docs ?

**Comment by jagraj** [comment]
@tobespc 
I am working on instructions which we need for this release. Will post here in few...

**Comment by jagraj** [comment]
Here are the instructions we need for 0.8.0 release. 

**Tekton Configuration for Remote Codewind install.**

1. Apply Tekton roles.

`kubectl apply -f https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.8.0/setup/install_che/codewind-tektonrole.yaml`

2. Apply Tekton cluster role bindings. To apply role bindings we need to replace <codewind-namespace> and <codewind-workspace-serviceaccount> from yaml file below.

    To findout <codewind-workspace-serviceaccount> use following commands.
     
    `Kubectl get sa`
	
```
NAME                SECRETS   AGE
builder             2         42h
codewind-k5p9o6aj   2         26h
default             2         42h
deployer            2         42h
keycloak-k5p9o6aj   2         26h

```

	Here my service account is : codewind-k5p9o6aj
	
	With the contents below create file called codewind-tektonbinding.yaml and replace <codewind-namespace> and <codewind-workspace-serviceaccount> values.
	In my above environment namespace: codewind and name: codewind-k5p9o6aj. 

    
```
#*******************************************************************************
# Copyright (c) 2019 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
#*******************************************************************************
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codewind-tektonbinding
subjects:
- kind: ServiceAccount
  namespace: <codewind-namespace>
  name: <codewind-workspace-serviceaccount>
roleRef:
  kind: ClusterRole
  name: codewind-tekton
  apiGroup: rbac.authorization.k8s.io
```

3. `kubectl apply -f codewind-tektonbinding.yaml`
