### ISSUE TITLE
Incubator repository from Appsody missing from the repository list

### ISSUE THREAD

**Issue by james-wallis** [eclipse/codewind#2379]
**Codewind version:** Master
**OS:** MacOS

**Description:**
The default `incubator` repository is missing from the repository list.
When `appsody` is first initialised into an completely new `codewind-workspace` volume it correctly adds a `repository.yaml` into the `/codewind-workspace/.appsody/repositories/repository.yaml` that contains the `incubator` repository (and the experimental one but we ignore this in Codewind).

Using my existing `codewind-workspace` I'm seeing a `repository.yaml` that is missing both these repositories but has another added:
```yaml
apiVersion: ""
generated: 0001-01-01T00:00:00Z
repositories:
- name: cc729f0f-f50d-5d02-9c9e-a2845952f127
  url: https://github.com/kabanero-io/collections/releases/download/v0.0.6/kabanero-index.yaml
  default: true
```

I'm not sure how its got in this state but I think that the Appsody extension should be ensuring that the `incubator` repository exists in the `repository.yaml`

**Thoughts**
Potentially add a new function to the extensions which resets them and re-adds all the repositories that Codewind knows about? `resetRepositories()`

**Steps to reproduce:**
1. Start Codewind (`./run.sh`)
2. `docker exec -it codewind-pfe bash`
3. Change the contents of `/codewind-workspace/.appsody/repository/repository.yaml` to be the yaml from above.
4. Restart Codewind (`./run.sh` again)
5. See that the `incubator` repository is missing.

**Workaround:** 

* Delete the `/codewind-workspace/.appsody/repository/repository.yaml` file but this will cause the repositories in the Codewind `repository_list.json` to be removed from the appsody extension.
