### ISSUE TITLE
SVT:Codewind workspace is blank on ROKS cluster

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind#3047]
**Codewind version:** 0.12.0
**OS:** RedHat

**Che version:** 7.9.2
**IDE extension version:** 0.12.0
**IDE version:** Theia 7.9.2
**Kubernetes cluster:**
ROKS 4.13.19

**Description:**

Andy and Myself got into this problem where Codewind 0.12.0 workspace is blank. We do not see same problem on on-premise OCP 4.3.18 cluster install. This happens only on public cloud.

![image](https://user-images.githubusercontent.com/713849/83066890-bd6c7780-a033-11ea-9844-3777d1a40024.png)

Here is the error in Theia container log. 

```
2020-05-27 19:26:46.899 root INFO unzipping the VS Code extension 'eclipse.codewind-theia.0.12.0.hxwfegtmqt.codewind-che.vsix' to directory: /tmp/vscode-unpacked/eclipse.codewind-theia.0.12.0.hxwfegtmqt.codewind-che.vsix
2020-05-27 19:26:46.931 root INFO [object Object]
2020-05-27 19:26:46.938 root ERROR Security problem: Unable to configure separate webviews domain:  Params: Error: Unable to get workspace containers. Cause: Cannot create Che API REST Client
    at CheApiServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-api-service.js:292:31)
    at step (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-api-service.js:38:23)
    at Object.throw (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-api-service.js:19:53)
    at rejected (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-api-service.js:11:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-27 19:26:46.984 root ERROR Uncaught Exception:  Params: [object Object]
```

**logs**

[pfe.txt](https://github.com/eclipse/codewind/files/4691492/pfe.txt)
[theia-logs.txt](https://github.com/eclipse/codewind/files/4691493/theia-logs.txt)

**Steps to reproduce:**
1. Install Che on ROKS 4.3.19 cluster.
2. Create Codewind 0.12.0 workspace.
3. After workspace start, workspace is blank.

**Workaround:**

**Comment by jagraj** [comment]
Opened this issue in che repo https://github.com/eclipse/che/issues/17031.

**Comment by tobespc** [comment]
This is raised against 0.12, does it also happen with 0.13 ?

**Comment by jagraj** [comment]
@tobespc 
Yes, we will have same issue with 0.13.0 release as well.

**Comment by johnmcollier** [comment]
@jagraj Can you try reproducing on Che 7.13.1? I can't reproduce

```

#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
#    IBM - Codewind specific settings
#
#  Instructions:
#    For instructions on installing Codewind for Eclipse Che using
#    this codewind-checluster.yaml file, see
#    https://www.eclipse.org/codewind/che-installinfo.html

apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codewind-che
spec:
  server:
    # server image used in Che deployment
    cheImage: 'quay.io/eclipse/che-server'
    # tag of an image used in Che deployment
    cheImageTag: '7.13.1'
    # image:tag used in Devfile registry deployment
    devfileRegistryImage: 'quay.io/eclipse/che-devfile-registry:7.13.1'
    # image:tag used in plugin registry deployment
    pluginRegistryImage: 'quay.io/eclipse/che-plugin-registry:7.13.1'
    # defaults to `che`. When set to `codeready`, CodeReady Workspaces is deployed
    # the difference is in images, labels, exec commands
    cheFlavor: ''
    # specifies a custom cluster role to user for the Che workspaces
    # Uses the default roles if left blank.
    cheWorkspaceClusterRole: 'eclipse-codewind'
    # when set to true the operator will attempt to get a secret in OpenShift router namespace
    # to add it to Java trust store of Che server. Requires cluster-admin privileges for operator service account
    selfSignedCert: true
    # TLS mode for Che. Make sure you either have public cert, or set selfSignedCert to true
    tlsSupport: true
    # protocol+hostname of a proxy server. Automatically added as JAVA_OPTS and https(s)_proxy
    # to Che server and workspaces containers
    proxyURL: ''
    # port of a proxy server
    proxyPort: ''
    # username for a proxy server
    proxyUser: ''
    # password for a proxy user
    proxyPassword: ''
    # a list of non-proxy hosts. Use | as delimiter, eg localhost|my.host.com|123.42.12.32
    nonProxyHosts: ''
    # sets mem request for server deployment. Defaults to 512Mi
    serverMemoryRequest: ''
    # sets mem limit for server deployment. Defaults to 1Gi
    serverMemoryLimit: ''
    # additional custom Che properties
    customCheProperties:
      CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN: "15"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "0"
      CHE_WORKSPACE_PLUGIN__BROKER_WAIT__TIMEOUT__MIN: "15"
  database:
    # when set to true, the operator skips deploying Postgres, and passes connection details of existing DB to Che server
    # otherwise a Postgres deployment is created
    externalDb: false
    # Postgres Database hostname that Che server uses to connect to. Defaults to postgres
    chePostgresHostName: ''
    # Postgres Database port that Che server uses to connect to. Defaults to 5432
    chePostgresPort: ''
    # Postgres user that Che server when making a db connection. Defaults to pgche
    chePostgresUser: ''
    # password of a postgres user. Auto-generated when left blank
    chePostgresPassword: ''
    # Postgres database name that Che server uses to connect to. Defaults to dbche
    chePostgresDb: ''
    # Postgres deployment in format image:tag. Defaults to registry.redhat.io/rhscl/postgresql-96-rhel7 (see pkg/deploy/defaults.go for latest tag)
    postgresImage: ''
  storage:
    # persistent volume claim strategy for Che server. Can be common (all workspaces PVCs in one volume),
    # per-workspace (one PVC per workspace for all declared volumes) and unique (one PVC per declared volume). Defaults to common
    pvcStrategy: 'per-workspace'
    # size of a persistent volume claim for workspaces. Defaults to 1Gi
    pvcClaimSize: '1Gi'
    # instruct Che server to launch a special pod to precreate a subpath in a PV
    preCreateSubPaths: true
    # image:tag for preCreateSubPaths jobs
    pvcJobsImage: ''
    # keep blank unless you need to use a non default storage class for Postgres PVC
    postgresPVCStorageClassName: ''
    # keep blank unless you need to use a non default storage class for workspace PVC(s)
    workspacePVCStorageClassName: ''

  auth:
    # instructs operator on whether or not to deploy Keycloak/RH SSO instance. When set to true provision connection details
    externalIdentityProvider: false
    # retrieved from respective route/ingress unless explicitly specified in CR (when ExternalKeycloak is true)
    identityProviderURL: ''
    # password for keycloak database user. Auto generated if left blank
    keycloakPostgresPassword: ''
    # desired admin username of Keycloak admin user (applicable only when externalIdentityProvider is false)
    identityProviderAdminUserName: ''
    # desired password of Keycloak admin user (applicable only when externalIdentityProvider is false)
    identityProviderPassword: 'admin'
    # name of a keycloak realm. This realm will be created, when externalIdentityProvider is true, otherwise passed to Che server
    identityProviderRealm: ''
    # id of a keycloak client. This client will be created, when externalIdentityProvider is false, otherwise passed to Che server
    identityProviderClientId: ''
    # instructs an Operator to enable OpenShift v3 identity provider in Keycloak,
    # as well as create respective oAuthClient and configure Che configMap accordingly
    openShiftoAuth: false
    # name of oAuthClient used in OpenShift v3 identity provider in Keycloak realm. Auto generated if left blank
    oAuthClientName: ''
    # secret used in oAuthClient. Auto generated if left blank
    oAuthSecret: ''
    # image:tag used in Keycloak deployment
    identityProviderImage: 'quay.io/eclipse/che-keycloak:7.13.1'
  k8s:
    # your global ingress domain
    ingressDomain: ''
    # kubernetes.io/ingress.class, defaults to nginx
    ingressClass: ''
    # IngressStrategy is the way ingresses are created.
    # Can be multi-host (host is explicitly provided in ingress, <ingress-name>-<namespace>.<global-ingress-domain>),
    # single-host (host is provided, path based rules, <ingress-domain>/path) and default-host *(no host is provided, path based rules)
    ingressStrategy: ''
    # secret name used for tls termination
    tlsSecretName: ''
    # FSGroup the Che POD and Workspace pod containers should run in  
    securityContextFsGroup: '' 
    # User the Che POD and Workspace pod containers should run as  
    securityContextRunAsUser: '' 
```
