### ISSUE TITLE
odo project creation based on generated templates

### ISSUE THREAD

**Issue by elsony** [eclipse/codewind#449]
Return index.json to Portal to allow creating project using odo templates

**Comment by GeekArthur** [comment]
The index.json file should be similar to this:
```
apiVersion: v2
stacks:
  - id: java-spring-boot2-liberty
    name: Spring Boot® on Open Liberty
    version: 0.1.7
    description: Spring Boot on Open Liberty & OpenJ9 using Maven
    license: Apache-2.0
    language: java
    maintainers:
     - name: Ozzy
       email: ozzy@ca.ibm.com
       github-id: bardweller
    default-template: default
    templates:
      - id: default
        url: https://github.com/appsody/stacks/releases/download/java-spring-boot2-liberty-v0.1.7/experimental.java-spring-boot2-liberty.v0.1.7.templates.default.tar.gz
  - id: nodejs-functions
    name: Node.js Functions
    version: 0.1.3
    description: Serverless runtime for Node.js functions
    license: Apache-2.0
    language: nodejs
    maintainers:
      - name: Chris Bailey
        email: cnbailey@gmail.com
        github-id: seabaylea
    default-template: simple
    templates:
      - id: simple
        url: https://github.com/appsody/stacks/releases/download/nodejs-functions-v0.1.3/experimental.nodejs-functions.templates.simple.tar.gz
  - id: quarkus
    name: Quarkus
    version: 0.1.5
    description: Quarkus runtime for running Java applications
    license: Apache-2.0
    language: java
    maintainers:
      - name: Paul Robinson
        email: probinso@redhat.com
        github-id: paulrobinson
    default-template: default
    templates:
      - id: default
        url: https://github.com/appsody/stacks/releases/download/quarkus-v0.1.5/experimental.quarkus.v0.1.5.templates.default.tar.gz
  - id: vertx
    name: Eclipse Vert.x
    version: 0.1.1
    description: Eclipse Vert.x runtime for running Java applications
    license: Eclipse Public License - Version 2.0
    language: java
    maintainers:
      - name: Erik Jan de Wit
        email: edewit@redhat.com
        github-id: edewit
    default-template: default
    templates:
      - id: default
        url: https://github.com/appsody/stacks/releases/download/vertx-v0.1.1/experimental.vertx.v0.1.1.templates.default.tar.gz
```
