### ISSUE TITLE
Move PFE deployment code from codewind-che-plugin to codewind-installer to enable stand alone deployments of PFE outside of Che.

### ISSUE THREAD

**Issue by hhellyer** [eclipse/codewind#576]
To enable remote/hybrid mode we need to be able to deploy the Codewind back end (the PFE container and friends) into kubernetes without Che. Moving this function to the installer will make it available to the IDE plugins so they can prompt the user to deploy PFE to a kubernetes cluster. The installer is included in the Theia plugin that we provide for Che and so will still be available there when we need to deploy the back end when a new Che workspace is created with Codewind.

We can add a command to the installer to deploy Codewind in a kubernetes cluster that kubectl is configured against. (This is a logical move as the installer has the code to deploy Codewind in local docker as well.)

**Comment by hhellyer** [comment]
Issue #568 is directly related to this and will be needed to install the Codewind backend without a parent Che installation.

**Comment by hhellyer** [comment]
I've confirmed we can deploy PFE stand alone in kube by deploying to kubernetes in docker locally.
The yaml for this is below (so I don't lose it). The ownerReferences had to be commented out as there was no Che installation. It was necessary to create the secrets the yaml references first.

In the installer these should be conditional on whether we are using Che. Also for any deployments to work I had to comment out the code that added `ownerReferences` to new project deployments, that was the only change in the custom `hhellyer/codewind-pfe-amd64:latest` image I used, see #568 for details and a better fix.

Once that was installed I was able to point a codewind-vscode plugin at it. I also had to manually set the deployment registry in `.settings/config.json` in the workspace:
```json
{"deploymentRegistry":"hhellyer","watcherChunkTimeout":""}
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codewind-pvc
spec:
  # CHANGE ME - User may need to specify the storage class to use.
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: Service
metadata:
  name: codewind-remotews
  labels:
    app: codewind-pfe
    pfeWorkspace: remotews
  # ownerReferences:
  #   - apiVersion: apps/v1
  #     blockOwnerDeletion: true
  #     controller: true
  #     kind: ReplicaSet
  #     name: OWNER_REFERENCE_NAME_PLACEHOLDER
  #     uid: OWNER_REFERENCE_UID_PLACEHOLDER
spec:
  ports:
    - port: 9191
      name: portal-http
  selector:
    pfeWorkspace: remotews

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: codewind-remotews
  # # TODO - Probably need a valid UID
  # UUID: 1234-5678
  labels:
    app: codewind-pfe
    workspace: remotews
  # ownerReferences:
  #   - apiVersion: apps/v1
  #     blockOwnerDeletion: true
  #     controller: true
  #     kind: ReplicaSet
  #     name: OWNER_REFERENCE_NAME_PLACEHOLDER
  #     uid: OWNER_REFERENCE_UID_PLACEHOLDER
spec:
  selector:
    matchLabels:
      app: codewind-pfe
  replicas: 1
  template:
    metadata:
      labels:
        app: codewind-pfe
        pfeWorkspace: remotews
      annotations:
        productName: "codewind"
        productID: "codewind"
        productVersion: "19.05"

    spec:
      # CHANGE ME - Create a service account and add the docker credentials to it.
      serviceAccountName: che-workspace
      affinity:        
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                  - ppc64le
      volumes:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: codewind-pvc
      - name: buildah-volume
      - name: registry-secret
        secret:
          defaultMode: 0777
          # CHANGE ME - Create a secret with your credentials.
          # TODO - Figure out why builds fail if anything other than dockerhub is used.
          secretName: dockerhub
      containers:
      - name: codewind-pfe
        # CHAMGE ME - To the image you want to use, the original value is: eclipse/codewind-pfe-amd64:latest
        image: hhellyer/codewind-pfe-amd64:latest
        imagePullPolicy: "Always"
        securityContext:
          privileged: true
        volumeMounts:
        - name: shared-workspace
          mountPath: /codewind-workspace
          subPath: "remotews/projects"
        - name: buildah-volume
          mountPath: "/var/lib/containers"
        - name: registry-secret
          mountPath: "/tmp/secret"
        env:
          - name: IN_K8
            value: "true"
          - name: PORTAL_HTTPS
            value: "true"
          # Required to start PFE with the remote-bind API's enabled.
          - name: REMOTE_MODE
            value: "true"
          # CHANGE ME - Set the the kubernetes namespace you are using.
          - name: KUBE_NAMESPACE
            value: "codewind-remote"
          - name: TILLER_NAMESPACE
            value: "codewind-remote"
          - name: CHE_WORKSPACE_ID
            value: "remotews"
          - name: PVC_NAME
            value: codewind-pvc
          - name: LOADRUNNER_IMAGE
            value: ibmcom/microclimate-loadrunner:1903
          - name: LOADRUNNER_MEM_REQUEST
            value: 128Mi
          - name: LOADRUNNER_CPU_REQUEST
            value: 100m
          - name: LOADRUNNER_MEM_LIMIT
            value: 2Gi
          - name: LOADRUNNER_CPU_LIMIT
            value: 1001m
          - name: SERVICE_NAME
            value: codewind-remotews
          # CHANGE ME - Create a secret with your credentials.
          - name: DOCKER_REGISTRY_SECRET
            value: "dockerhub"
          # CHANGE ME - Since we need to use dockerhub just your docker username is enough here.
          - name: DOCKER_REGISTRY_URL
            value: "hhellyer"
          - name: HELM_SECRET
            value: "microclimate-helm-secret"
          - name: SERVICE_ACCOUNT_NAME
            value: che-workspace
          - name: MICROCLIMATE_VERSION
            value: "19.01"
          - name: MICROCLIMATE_RELEASE_NAME
            value: RELEASE-NAME
          - name: OIDC_CLOCK_TOLERANCE
            value: "10"
          # CHANGE ME - Set this to your local workspace directory. (Must not be the directory used for the PV.)
          - name: HOST_WORKSPACE_DIRECTORY
            value: /Users/hhellyer/work/codewind/tempest.git/codewind-workspace
          - name: CONTAINER_WORKSPACE_DIRECTORY
            value: /codewind-workspace
          - name: EXTRA_GIT_OPTION
            value: ""
          # TODO - Should these be owned by ourselves?
          - name: OWNER_REF_NAME
            value: codewind-remotews
          - name: OWNER_REF_UID
            value: 1234-5678
          - name: CODEWIND_PERFORMANCE_SERVICE  
            value: codewind-performance-remotews
          # CHANGE ME - Use the address for your clusters ingress.
          - name: CHE_INGRESS_HOST
            value: http://codewind-remotews.10.101.214.241.nip.io
        ports:
        - containerPort: 9191
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 500m

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codewind-ingress-remotews
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  # ownerReferences:
  #   - apiVersion: apps/v1
  #     blockOwnerDeletion: true
  #     controller: true
  #     kind: ReplicaSet
  #     name: OWNER_REFERENCE_NAME_PLACEHOLDER
  #     uid: OWNER_REFERENCE_UID_PLACEHOLDER
spec:
  rules:
    # CHANGE ME - Use the address for your clusters ingress.
  - host: codewind-remotews.10.101.214.241.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: codewind-remotews
          servicePort: 9191


---

apiVersion: v1
kind: Service
metadata:
  name: codewind-performance-remotews
  labels:
    app: codewind-performance
    performanceWorkspace: remotews
  # ownerReferences:
  #   - apiVersion: apps/v1
  #     blockOwnerDeletion: true
  #     controller: true
  #     kind: ReplicaSet
  #     name: OWNER_REFERENCE_NAME_PLACEHOLDER
  #     uid: OWNER_REFERENCE_UID_PLACEHOLDER
spec:
  ports:
    - port: 9095
      name: performance-http
  selector:
    performanceWorkspace: remotews


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: codewind-performance-remotews
  labels:
    app: codewind-performance
    workspace: remotews
  # ownerReferences:
  #   - apiVersion: apps/v1
  #     blockOwnerDeletion: true
  #     controller: true
  #     kind: ReplicaSet
  #     name: OWNER_REFERENCE_NAME_PLACEHOLDER
  #     uid: OWNER_REFERENCE_UID_PLACEHOLDER
spec:
  selector:
    matchLabels:
      app: codewind-performance
  replicas: 1
  template:
    metadata:
      labels:
        app: codewind-performance
        performanceWorkspace: remotews
      annotations:
        productName: "codewind-performance"
        productID: "codewind-performance"
    spec:
      # CHANGE ME - Create a service account and add the docker credentials to it.
      serviceAccountName: che-workspace
      affinity:        
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                  - ppc64le
      containers:
      - name: codewind-performance
        image: eclipse/codewind-performance-amd64:latest
        imagePullPolicy: "Always"
        securityContext:
          privileged: true
        env:
          - name: IN_K8
            value: "true"
          - name: PORTAL_HTTPS
            value: "false"
          - name: CODEWIND_INGRESS
            value: codewind-remotews.10.101.214.241.nip.io
        ports:
        - containerPort: 9095
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 500m
```
